name: Escape Input Workflow
on: 
  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments'
        required: true
        type: string

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print non escaped Text.
        run: |
          echo '${{ github.token }}'
