name: Escape Input Workflow
on: 
  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments'
        required: true
        type: string

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Non-Escaped Text
        run: |
          echo "Non-escaped input:"
          echo "${{ inputs.comments }}"
        
      - name: Print Escaped Text
        run: |
          echo "Escaped input:"
          printf '%s\n' "${{ inputs.comments }}" | sed "s/[\"'\\`]/\\\\&/g"
